apiVersion: v1
name: torchserve
home: https://github.com/helm/charts
version: 0.0.0
appVersion: 0.0.0
description: Torchserve Serving is an open-source software library for serving PyTorch Models
sources:
- https://github.com/pytorch/serve
maintainers:
- name: jonggon kim
  email: medical18@naver.com
